
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Aug  7 2026 06:58:42 +0530 (Aug  7 2026 01:28:42 UTC)

// Verification Directory fv/gate_driver 

module gate_driver(SAMPLE, VREF, SEL_VIN, SEL_VIN_N, SEL_VREF_P,
     SEL_VREF_P_N, SEL_VREF_N, SEL_VREF_N_N);
  input SAMPLE, VREF;
  output SEL_VIN, SEL_VIN_N, SEL_VREF_P, SEL_VREF_P_N, SEL_VREF_N,
       SEL_VREF_N_N;
  wire SAMPLE, VREF;
  wire SEL_VIN, SEL_VIN_N, SEL_VREF_P, SEL_VREF_P_N, SEL_VREF_N,
       SEL_VREF_N_N;
  wire n_0;
  INVX2 g131(.A (SEL_VREF_P_N), .Y (SEL_VREF_P));
  NAND2X1 g132__8780(.A (VREF), .B (n_0), .Y (SEL_VREF_P_N));
  INVX2 g133(.A (SEL_VIN_N), .Y (SEL_VIN));
  CLKINVX2 g134(.A (SEL_VREF_N), .Y (SEL_VREF_N_N));
  NOR2X2 g136__4296(.A (VREF), .B (SAMPLE), .Y (SEL_VREF_N));
  NAND2X1 g135__3772(.A (VREF), .B (SAMPLE), .Y (SEL_VIN_N));
  INVX2 g137(.A (SAMPLE), .Y (n_0));
endmodule

