
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: May  4 2026 01:07:08 +0530 (May  3 2026 19:37:08 UTC)

// Verification Directory fv/test_inverter 

module test_inverter(A, B);
  input A;
  output B;
  wire A;
  wire B;
  CLKINVX2 g2(.A (A), .Y (B));
endmodule

